#!/bin/bash

cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/tmp.aae82c60" && echo "/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/tmp.aae82c60")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution

)
outc7cb0df6="${tmpDir}/out.$$" errc7cb0df6="${tmpDir}/err.$$"
mkfifo "$outc7cb0df6" "$errc7cb0df6"
trap 'rm "$outc7cb0df6" "$errc7cb0df6"' EXIT
tee '/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution/stdout' < "$outc7cb0df6" &
tee '/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution/stderr' < "$errc7cb0df6" >&2 &
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution


set -euo pipefail
if [[ adrenal_1_fastqc.html != "adrenal_1_fastqc.html" ]];then 
  ln -s /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/inputs/618620788/adrenal_1_fastqc.html "adrenal_1_fastqc.html"
else
  ln -s /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/inputs/618620788/adrenal_1_fastqc.html
fi
)  > "$outc7cb0df6" 2> "$errc7cb0df6"
echo $? > /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution
sync


)
mv /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution/rc.tmp /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateHtml/execution/rc
