#!/bin/bash

cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/tmp.4a956652" && echo "/cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/tmp.4a956652")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution

)
out53c2f224="${tmpDir}/out.$$" err53c2f224="${tmpDir}/err.$$"
mkfifo "$out53c2f224" "$err53c2f224"
trap 'rm "$out53c2f224" "$err53c2f224"' EXIT
tee '/cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution/stdout' < "$out53c2f224" &
tee '/cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution/stderr' < "$err53c2f224" >&2 &
(
cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution


set -euo pipefail
FASTQC=$(which fastqc)
JAVA=$(which java)
perl $FASTQC /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/inputs/2105055555/adrenal_1.fastq.gz --java=$JAVA --noextract --outdir "."
)  > "$out53c2f224" 2> "$err53c2f224"
echo $? > /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution
sync


)
mv /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution/rc.tmp /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateFastQC/execution/rc
