#!/bin/bash

cd /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/tmp.f71e0b2f" && echo "/cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/tmp.f71e0b2f")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution

)
out5819c3b9="${tmpDir}/out.$$" err5819c3b9="${tmpDir}/err.$$"
mkfifo "$out5819c3b9" "$err5819c3b9"
trap 'rm "$out5819c3b9" "$err5819c3b9"' EXIT
tee '/cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution/stdout' < "$out5819c3b9" &
tee '/cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution/stderr' < "$err5819c3b9" >&2 &
(
cd /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution


set -euo pipefail
FASTQC=$(which fastqc)
JAVA=$(which java)
perl $FASTQC /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/inputs/2105055555/adrenal_1.fastq.gz --java=$JAVA --noextract --outdir "."
)  > "$out5819c3b9" 2> "$err5819c3b9"
echo $? > /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution
sync


)
mv /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution/rc.tmp /cromwell-executions/fastQC/5819c3b9-7cbc-433d-a66d-2c06e6e2c79d/call-firstMateFastQC/execution/rc
