#!/bin/bash

cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/tmp.ae48f011" && echo "/cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/tmp.ae48f011")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution

)
out0f906048="${tmpDir}/out.$$" err0f906048="${tmpDir}/err.$$"
mkfifo "$out0f906048" "$err0f906048"
trap 'rm "$out0f906048" "$err0f906048"' EXIT
tee '/cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution/stdout' < "$out0f906048" &
tee '/cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution/stderr' < "$err0f906048" >&2 &
(
cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution


set -euo pipefail
if [[ adrenal_2_fastqc.zip != "adrenal_2_fastqc.zip" ]];then 
  ln -s /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/inputs/881567218/adrenal_2_fastqc.zip "adrenal_2_fastqc.zip"
else
  ln -s /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/inputs/881567218/adrenal_2_fastqc.zip
fi
)  > "$out0f906048" 2> "$err0f906048"
echo $? > /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution
sync


)
mv /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution/rc.tmp /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateZip/execution/rc
