#!/bin/bash

cd /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/tmp.cf27d62b" && echo "/cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/tmp.cf27d62b")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution

)
out731631fa="${tmpDir}/out.$$" err731631fa="${tmpDir}/err.$$"
mkfifo "$out731631fa" "$err731631fa"
trap 'rm "$out731631fa" "$err731631fa"' EXIT
tee '/cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution/stdout' < "$out731631fa" &
tee '/cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution/stderr' < "$err731631fa" >&2 &
(
cd /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution


set -euo pipefail
if [[ adrenal_2_fastqc.html != "adrenal_2_fastqc.html" ]];then 
  ln -s /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/inputs/1023281997/adrenal_2_fastqc.html "adrenal_2_fastqc.html"
else
  ln -s /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/inputs/1023281997/adrenal_2_fastqc.html
fi
)  > "$out731631fa" 2> "$err731631fa"
echo $? > /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution
sync


)
mv /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution/rc.tmp /cromwell-executions/fastQC/731631fa-68d6-40aa-93c9-29cf96057cee/call-secondMateHtml/execution/rc
