#!/bin/bash

cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/tmp.2384dd7e" && echo "/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/tmp.2384dd7e")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution

)
out9f3f581d="${tmpDir}/out.$$" err9f3f581d="${tmpDir}/err.$$"
mkfifo "$out9f3f581d" "$err9f3f581d"
trap 'rm "$out9f3f581d" "$err9f3f581d"' EXIT
tee '/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution/stdout' < "$out9f3f581d" &
tee '/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution/stderr' < "$err9f3f581d" >&2 &
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution


set -euo pipefail
if [[ adrenal_1_fastqc.zip != "adrenal_1_fastqc.zip" ]];then 
  ln -s /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/inputs/1877946799/adrenal_1_fastqc.zip "adrenal_1_fastqc.zip"
else
  ln -s /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/inputs/1877946799/adrenal_1_fastqc.zip
fi
)  > "$out9f3f581d" 2> "$err9f3f581d"
echo $? > /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution
sync


)
mv /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution/rc.tmp /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateZip/execution/rc
