#!/bin/bash

cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/tmp.0ea5c43f" && echo "/cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/tmp.0ea5c43f")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution

)
out0f906048="${tmpDir}/out.$$" err0f906048="${tmpDir}/err.$$"
mkfifo "$out0f906048" "$err0f906048"
trap 'rm "$out0f906048" "$err0f906048"' EXIT
tee '/cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution/stdout' < "$out0f906048" &
tee '/cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution/stderr' < "$err0f906048" >&2 &
(
cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution


set -euo pipefail
FASTQC=$(which fastqc)
JAVA=$(which java)
perl $FASTQC /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/inputs/2105055555/adrenal_2.fastq.gz --java=$JAVA --noextract --outdir "."
)  > "$out0f906048" 2> "$err0f906048"
echo $? > /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution
sync


)
mv /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution/rc.tmp /cromwell-executions/fastQC/0f906048-6e6f-415e-8548-46dbf3a7f637/call-secondMateFastQC/execution/rc
