#!/bin/bash

cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/tmp.53587889" && echo "/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/tmp.53587889")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution

)
outc7cb0df6="${tmpDir}/out.$$" errc7cb0df6="${tmpDir}/err.$$"
mkfifo "$outc7cb0df6" "$errc7cb0df6"
trap 'rm "$outc7cb0df6" "$errc7cb0df6"' EXIT
tee '/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution/stdout' < "$outc7cb0df6" &
tee '/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution/stderr' < "$errc7cb0df6" >&2 &
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution


set -euo pipefail
if [[ adrenal_1_fastqc.zip != "adrenal_1_fastqc.zip" ]];then 
  ln -s /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/inputs/618620788/adrenal_1_fastqc.zip "adrenal_1_fastqc.zip"
else
  ln -s /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/inputs/618620788/adrenal_1_fastqc.zip
fi
)  > "$outc7cb0df6" 2> "$errc7cb0df6"
echo $? > /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution
sync


)
mv /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution/rc.tmp /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-firstMateZip/execution/rc
