#!/bin/bash

cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/tmp.192a9e55" && echo "/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/tmp.192a9e55")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution

)
out9797ad08="${tmpDir}/out.$$" err9797ad08="${tmpDir}/err.$$"
mkfifo "$out9797ad08" "$err9797ad08"
trap 'rm "$out9797ad08" "$err9797ad08"' EXIT
tee '/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution/stdout' < "$out9797ad08" &
tee '/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution/stderr' < "$err9797ad08" >&2 &
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution


set -euo pipefail
if [[ adrenal_2_fastqc.html != "adrenal_2_fastqc.html" ]];then 
  ln -s /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/inputs/241217041/adrenal_2_fastqc.html "adrenal_2_fastqc.html"
else
  ln -s /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/inputs/241217041/adrenal_2_fastqc.html
fi
)  > "$out9797ad08" 2> "$err9797ad08"
echo $? > /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution
sync


)
mv /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution/rc.tmp /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateHtml/execution/rc
