#!/bin/bash

cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/tmp.e6cbe77e" && echo "/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/tmp.e6cbe77e")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution

)
outc7cb0df6="${tmpDir}/out.$$" errc7cb0df6="${tmpDir}/err.$$"
mkfifo "$outc7cb0df6" "$errc7cb0df6"
trap 'rm "$outc7cb0df6" "$errc7cb0df6"' EXIT
tee '/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution/stdout' < "$outc7cb0df6" &
tee '/cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution/stderr' < "$errc7cb0df6" >&2 &
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution


set -euo pipefail
FASTQC=$(which fastqc)
JAVA=$(which java)
perl $FASTQC /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/inputs/2105055555/adrenal_2.fastq.gz --java=$JAVA --noextract --outdir "."
)  > "$outc7cb0df6" 2> "$errc7cb0df6"
echo $? > /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution
sync


)
mv /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution/rc.tmp /cromwell-executions/fastQC/c7cb0df6-93ff-4919-bf05-a178ac66892b/call-secondMateFastQC/execution/rc
