#!/bin/bash

cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/tmp.dea733ad" && echo "/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/tmp.dea733ad")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution

)
out9f3f581d="${tmpDir}/out.$$" err9f3f581d="${tmpDir}/err.$$"
mkfifo "$out9f3f581d" "$err9f3f581d"
trap 'rm "$out9f3f581d" "$err9f3f581d"' EXIT
tee '/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution/stdout' < "$out9f3f581d" &
tee '/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution/stderr' < "$err9f3f581d" >&2 &
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution


set -euo pipefail
FASTQC=$(which fastqc)
JAVA=$(which java)
perl $FASTQC /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/inputs/2105055555/adrenal_1.fastq.gz --java=$JAVA --noextract --outdir "."
)  > "$out9f3f581d" 2> "$err9f3f581d"
echo $? > /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution
sync


)
mv /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution/rc.tmp /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateFastQC/execution/rc
