#!/bin/bash

cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/tmp.32006f8d" && echo "/cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/tmp.32006f8d")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution

)
out53c2f224="${tmpDir}/out.$$" err53c2f224="${tmpDir}/err.$$"
mkfifo "$out53c2f224" "$err53c2f224"
trap 'rm "$out53c2f224" "$err53c2f224"' EXIT
tee '/cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution/stdout' < "$out53c2f224" &
tee '/cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution/stderr' < "$err53c2f224" >&2 &
(
cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution


set -euo pipefail
if [[ adrenal_1_fastqc.zip != "adrenal_1_fastqc.zip" ]];then 
  ln -s /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/inputs/1987058195/adrenal_1_fastqc.zip "adrenal_1_fastqc.zip"
else
  ln -s /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/inputs/1987058195/adrenal_1_fastqc.zip
fi
)  > "$out53c2f224" 2> "$err53c2f224"
echo $? > /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution
sync


)
mv /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution/rc.tmp /cromwell-executions/fastQC/53c2f224-0823-4f47-9679-77d66c6a077d/call-firstMateZip/execution/rc
