#!/bin/bash

cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/tmp.d2b9d1db" && echo "/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/tmp.d2b9d1db")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution

)
out9f3f581d="${tmpDir}/out.$$" err9f3f581d="${tmpDir}/err.$$"
mkfifo "$out9f3f581d" "$err9f3f581d"
trap 'rm "$out9f3f581d" "$err9f3f581d"' EXIT
tee '/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution/stdout' < "$out9f3f581d" &
tee '/cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution/stderr' < "$err9f3f581d" >&2 &
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution


set -euo pipefail
if [[ adrenal_1_fastqc.html != "adrenal_1_fastqc.html" ]];then 
  ln -s /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/inputs/1877946799/adrenal_1_fastqc.html "adrenal_1_fastqc.html"
else
  ln -s /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/inputs/1877946799/adrenal_1_fastqc.html
fi
)  > "$out9f3f581d" 2> "$err9f3f581d"
echo $? > /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution
sync


)
mv /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution/rc.tmp /cromwell-executions/fastQC/9f3f581d-c640-4c15-931f-2658b19681a4/call-firstMateHtml/execution/rc
