#!/bin/bash

cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/tmp.a685bc93" && echo "/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/tmp.a685bc93")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution

)
out9797ad08="${tmpDir}/out.$$" err9797ad08="${tmpDir}/err.$$"
mkfifo "$out9797ad08" "$err9797ad08"
trap 'rm "$out9797ad08" "$err9797ad08"' EXIT
tee '/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution/stdout' < "$out9797ad08" &
tee '/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution/stderr' < "$err9797ad08" >&2 &
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution


set -euo pipefail
FASTQC=$(which fastqc)
JAVA=$(which java)
perl $FASTQC /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/inputs/2105055555/adrenal_1.fastq.gz --java=$JAVA --noextract --outdir "."
)  > "$out9797ad08" 2> "$err9797ad08"
echo $? > /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution
sync


)
mv /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution/rc.tmp /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-firstMateFastQC/execution/rc
