#!/bin/bash

cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution
tmpDir=$(mkdir -p "/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/tmp.022e92c1" && echo "/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/tmp.022e92c1")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution

)
out9797ad08="${tmpDir}/out.$$" err9797ad08="${tmpDir}/err.$$"
mkfifo "$out9797ad08" "$err9797ad08"
trap 'rm "$out9797ad08" "$err9797ad08"' EXIT
tee '/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution/stdout' < "$out9797ad08" &
tee '/cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution/stderr' < "$err9797ad08" >&2 &
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution


set -euo pipefail
if [[ adrenal_2_fastqc.zip != "adrenal_2_fastqc.zip" ]];then 
  ln -s /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/inputs/241217041/adrenal_2_fastqc.zip "adrenal_2_fastqc.zip"
else
  ln -s /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/inputs/241217041/adrenal_2_fastqc.zip
fi
)  > "$out9797ad08" 2> "$err9797ad08"
echo $? > /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution
sync


)
mv /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution/rc.tmp /cromwell-executions/fastQC/9797ad08-c0db-495d-a55e-3a3e5840a3e6/call-secondMateZip/execution/rc
